# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mendoza [TIC]
email: mdztic@gmail.com
description:  # this means to ignore newlines until "baseurl:"
   Mendoza [TIC] = Mendoza Job[s] + Evento[s]
  
  
  
baseurl: "/mdztic.github.io" # the subpath of your site, e.g. /blog
# url: "http://mdztic.github.io" # the base hostname & protocol for your site

#sidebar
default-image: "pythonar.png" # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

# #footer
# built-by: webjeda | Python Mendoza
copyright:
   name: Mendoza [TIC]
   link: 'http://mdztic.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus-shortname: webjeda-demo

#social
facebook: https://www.facebook.com/mdztic/
twitter: http://twitter.com/mdztic
github: http://github.com/mdztic

#facebook like box
# fb-app-id: 549480635219583
# fb-page-url: https://www.facebook.com/webjeda/
# fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

